[project]
version="0.1.0"
name="pywebview-react-app"
requires-python = ">=3.11"
dependencies = [
    "pywebview",
    "plotly",
    "pandas"
]
[project.optional-dependencies]
linux = ['pywebview[qt]']
dev = [
    "ruff",
    "reloadium"
]
